vision_backbone: resnet18
touch_backbone: resnet18

vision_backbone_checkpoint: './exp_1000/SpectroVision_vision/vision_backbone.pth'
touch_backbone_checkpoint: './exp_1000/SpectroVision_touch/touch_backbone.pth'
vision_mlp_checkpoint: './exp_1000/SpectroVision_vision/vision_mlp.pth'
touch_mlp_checkpoint: './exp_1000/SpectroVision_touch/touch_mlp.pth'
# classifier_checkpoint: './exp_1000/test/classifier.pth'